name: CI

on:
  push:
    branches:
      - master
      - Ladder
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - 'docs/**'
      - 'maps/**'
      - 'CREDITS'
      - 'LICENSE'
      - '**.md'
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - 'docs/**'
      - 'maps/**'
      - 'CREDITS'
      - 'LICENSE'
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-22.04]
        build_type: [Release, Debug]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install latest CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

#
#  ladder_build:
#    runs-on: ubuntu-22.04
#
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          submodules: recursive
#
#      - name: Configure
#        run: |
#          cmake \
#            -B ${{env.BUILD_DIR}} \
#            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
#            -DBUILD_SC2_RENDERER=OFF \
#            -DBUILD_API_EXAMPLES=OFF \
#            -DBUILD_API_TESTS=OFF \
#            -DSC2_VERSION=4.10.0
#
#      - name: Build
#        run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}} --parallel 2
